//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

declare module Taz.Domain {
	export interface IEntity
	{
		id?: number;
	}
	export interface IFakeEntity extends Taz.Domain.IEntity
	{
		name?: string;
		rootId?: number;
		parentId?: number;
		parent?: Taz.Domain.IFakeEntity;
		root?: Taz.Domain.IFakeEntity;
		children?: Taz.Domain.IFakeEntity[];
		rootCollection?: Taz.Domain.IFakeEntity[];
	}
}
